#!/usr/bin/env python3
"""
Example: Using MCP Configuration in InsightOS

This script demonstrates how to integrate MCP servers with the InsightOS agent.
"""

from pathlib import Path
from mcp_servers import get_mcp_config


def example_basic_usage():
    """Basic configuration usage"""
    print("=== Basic MCP Configuration ===\n")
    
    config = get_mcp_config()
    
    # Show current setup
    print(f"Configuration file: {config.config_file}")
    print(f"Output directory: {config.get_output_dir()}")
    print(f"Enabled servers: {list(config.get_enabled_servers().keys())}")
    
    # Security check
    is_safe = config.validate_filesystem_access()
    print(f"\n✓ Filesystem access is {'SAFE' if is_safe else 'UNSAFE'}")
    

def example_security_validation():
    """Validate security settings before agent operations"""
    print("\n=== Security Validation ===\n")
    
    config = get_mcp_config()
    summary = config.get_security_summary()
    
    print("Security Summary:")
    for key, value in summary.items():
        print(f"  {key}: {value}")
    
    # Ensure filesystem is restricted
    if not summary['filesystem_restricted']:
        print("\n⚠️  WARNING: Filesystem access is not restricted!")
        print("   Agent could potentially access user files.")
        return False
    
    print("\n✓ All security checks passed")
    return True


def example_agent_integration():
    """Show how to use with Claude API"""
    print("\n=== Agent Integration Example ===\n")
    
    config = get_mcp_config()
    
    # Get MCP config for Claude
    claude_config = config.export_to_claude_config()
    
    # Build system prompt with safety instructions
    system_prompt = f"""You are an AI assistant for InsightOS, a document knowledge system.

CAPABILITIES:
- Search through user's indexed documents (via RAG)
- Create summaries, reports, and synthesized documents
- Extract structured data from documents
- Use knowledge graph for entity tracking

FILE WRITING RULES (CRITICAL):
1. You can ONLY write new files to: {config.get_output_dir()}
2. You CANNOT modify user's original documents
3. All generated files must include metadata showing they were created by InsightOS
4. Include provenance: date, source documents used, and purpose

EXAMPLE TASKS:
- "Summarize all documents about AI ethics" → Create markdown summary in Generated/
- "Extract action items from meeting notes" → Create CSV in Generated/
- "Create a project proposal template" → Create template in Generated/

Available MCP servers: {list(config.get_enabled_servers().keys())}
"""
    
    print("System prompt configured with:")
    print(f"  - Output directory restriction: {config.get_output_dir()}")
    print(f"  - Available servers: {list(config.get_enabled_servers().keys())}")
    print(f"  - Safety guidelines: Included")


def example_file_generation():
    """Demonstrate proper file generation with metadata"""
    print("\n=== File Generation Example ===\n")
    
    from datetime import datetime
    
    config = get_mcp_config()
    output_dir = config.get_output_dir()
    
    # Create subdirectories
    summaries_dir = output_dir / "summaries"
    summaries_dir.mkdir(exist_ok=True)
    
    # Generate example summary file
    summary_file = summaries_dir / f"AI_Ethics_Summary_{datetime.now().strftime('%Y%m%d')}.md"
    
    content = f"""---
title: AI Ethics Summary
generated_by: InsightOS
date: {datetime.now().isoformat()}
source_documents: 
  - ai_ethics_paper_1.pdf
  - ai_ethics_paper_2.pdf
  - ethics_guidelines.docx
document_count: 3
---

# AI Ethics: Key Themes Across Documents

## Overview
This summary synthesizes insights from 3 documents in your knowledge base on AI ethics.

## Key Themes

### 1. Transparency and Explainability
Multiple documents emphasize the importance of making AI decisions interpretable...

### 2. Bias and Fairness
Concerns about algorithmic bias appear across all sources...

### 3. Privacy and Data Protection
All documents highlight GDPR and HIPAA compliance requirements...

## Recommendations
Based on the synthesized knowledge:
- Implement bias testing in ML pipelines
- Regular ethics audits for AI systems
- User consent frameworks for data collection

---
*Generated by InsightOS on {datetime.now().strftime('%Y-%m-%d %H:%M')}*
*This is a synthesized document. Refer to original sources for complete details.*
"""
    
    with open(summary_file, 'w') as f:
        f.write(content)
    
    print(f"✓ Generated example summary: {summary_file}")
    print(f"  Location: {summary_file.relative_to(Path.home())}")
    print(f"  Size: {summary_file.stat().st_size} bytes")


def example_server_management():
    """Manage MCP servers"""
    print("\n=== Server Management ===\n")
    
    from mcp_servers import MCPServerConfig
    
    config = get_mcp_config()
    
    # Add a custom server (example)
    custom_server = MCPServerConfig(
        name="example-custom",
        command="node",
        args=["./my-server.js"],
        enabled=False,
        description="Custom server example (not actually installed)"
    )
    
    # Don't actually add it in this example
    # config.add_server(custom_server)
    
    print("Current servers:")
    for name, server in config.servers.items():
        status = "✓ Enabled" if server.enabled else "✗ Disabled"
        print(f"  {status} - {name}: {server.description}")
    
    # Show how to enable/disable
    print("\nServer Management Methods:")
    print("  config.enable_server('brave-search')")
    print("  config.disable_server('filesystem')")
    print("  config.add_server(custom_server)")
    print("  config.remove_server('server-name')")


def main():
    """Run all examples"""
    try:
        example_basic_usage()
        example_security_validation()
        example_agent_integration()
        example_file_generation()
        example_server_management()
        
        print("\n" + "="*60)
        print("✓ All examples completed successfully!")
        print("="*60)
        
    except Exception as e:
        print(f"\n✗ Error: {e}")
        raise


if __name__ == "__main__":
    main()