"""
File Generation Utilities
Helpers for creating agent-generated files with proper metadata
"""

from pathlib import Path
from datetime import datetime
from typing import List, Optional
from mcp_servers import get_mcp_config


class FileGenerator:
    """Helper for generating files with proper metadata"""
    
    def __init__(self):
        self.mcp_config = get_mcp_config()
        self.output_dir = self.mcp_config.get_output_dir()
    
    def create_summary(
        self,
        title: str,
        content: str,
        source_docs: List[str],
        query: Optional[str] = None
    ) -> Path:
        """
        Create a summary file with metadata
        
        Args:
            title: Summary title
            content: Main content
            source_docs: List of source document names
            query: User's original query (optional)
            
        Returns:
            Path to created file
        """
        # Create summaries subdirectory
        summaries_dir = self.output_dir / "summaries"
        summaries_dir.mkdir(exist_ok=True)
        
        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d")
        safe_title = title.replace(" ", "_").replace("/", "-")
        filename = f"{safe_title}_{timestamp}.md"
        filepath = summaries_dir / filename
        
        # Build metadata
        metadata = self._build_metadata(
            title=title,
            source_docs=source_docs,
            query=query
        )
        
        # Write file
        full_content = f"{metadata}\n\n{content}\n\n{self._build_footer()}"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(full_content)
        
        print(f"✓ Created summary: {filepath}")
        return filepath
    
    def create_report(
        self,
        title: str,
        content: str,
        source_docs: List[str],
        format: str = "md"
    ) -> Path:
        """Create a report file with metadata"""
        reports_dir = self.output_dir / "reports"
        reports_dir.mkdir(exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d")
        safe_title = title.replace(" ", "_")
        filename = f"{safe_title}_{timestamp}.{format}"
        filepath = reports_dir / filename
        
        metadata = self._build_metadata(title=title, source_docs=source_docs)
        full_content = f"{metadata}\n\n{content}\n\n{self._build_footer()}"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(full_content)
        
        print(f"✓ Created report: {filepath}")
        return filepath
    
    def create_extract(
        self,
        filename: str,
        content: str,
        source_docs: List[str],
        format: str = "csv"
    ) -> Path:
        """Create a data extract file"""
        extracts_dir = self.output_dir / "extracts"
        extracts_dir.mkdir(exist_ok=True)
        
        timestamp = datetime.now().strftime("%Y%m%d")
        full_filename = f"{filename}_{timestamp}.{format}"
        filepath = extracts_dir / full_filename
        
        # For CSV/TSV, add comment header
        if format in ["csv", "tsv"]:
            header = f"# Generated by InsightOS on {datetime.now().isoformat()}\n"
            header += f"# Source documents: {', '.join(source_docs)}\n"
            full_content = header + content
        else:
            metadata = self._build_metadata(title=filename, source_docs=source_docs)
            full_content = f"{metadata}\n\n{content}"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(full_content)
        
        print(f"✓ Created extract: {filepath}")
        return filepath
    
    def _build_metadata(
        self,
        title: str,
        source_docs: List[str],
        query: Optional[str] = None
    ) -> str:
        """Build YAML frontmatter metadata"""
        metadata_lines = [
            "---",
            f"title: {title}",
            f"generated_by: InsightOS",
            f"date: {datetime.now().isoformat()}",
            f"source_documents:"
        ]
        
        for doc in source_docs:
            metadata_lines.append(f"  - {doc}")
        
        metadata_lines.append(f"document_count: {len(source_docs)}")
        
        if query:
            metadata_lines.append(f"query: \"{query}\"")
        
        metadata_lines.append("---")
        
        return "\n".join(metadata_lines)
    
    def _build_footer(self) -> str:
        """Build file footer"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        return f"""---
*Generated by InsightOS on {timestamp}*
*This is a synthesized document. Refer to original sources for complete details.*"""


# Singleton instance
_file_generator = None

def get_file_generator() -> FileGenerator:
    """Get or create file generator singleton"""
    global _file_generator
    if _file_generator is None:
        _file_generator = FileGenerator()
    return _file_generator